# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b7IUfKZ9Xs7aFqsVdG_VzaG9Hsmf1GI5
"""

# =====================================================================
# 步驟 1: 匯入必備套件與掛載 Google Drive
# =====================================================================
import os
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

print("正在啟用 Google 雲端硬碟連線... 請在彈出視窗中點擊『允許存取』")
from google.colab import drive
drive.mount('/content/drive')

# =====================================================================
# 步驟 2: 設定資料夾路徑與「資料增強」設定 (專為少量圖片優化)
# =====================================================================
# 💡 這裡的路徑對應你 Google Drive 的「anime_style_project/dataset/」
data_dir = '/content/drive/MyDrive/anime_style_project/dataset'
# 檢查路徑是否存在，避免路徑打錯導致程式崩潰
if not os.path.exists(data_dir):
    raise ValueError(f"❌ 找不到路徑：{data_dir}，請檢查雲端硬碟的資料夾名稱是否拼錯！")

print("👉 成功找到資料夾，正在初始化圖片產生器並進行資料增強...")

datagen = ImageDataGenerator(
    rescale=1./255,            # 將像素值從 0~255 轉為 0~1
    rotation_range=40,         # 隨機旋轉角度最大達 40 度 (拯救少量資料)
    width_shift_range=0.2,     # 隨機水平移動
    height_shift_range=0.2,    # 隨機垂直移動
    shear_range=0.2,           # 隨機歪斜變形
    zoom_range=0.2,            # 隨機放大縮小
    horizontal_flip=True,      # 隨機左右翻轉
    fill_mode='nearest',       # 空白邊緣補全
    validation_split=0.2       # 自動切出 20% 的圖片用來檢驗 AI 的學習成果
)

# 讀取訓練資料 (80%)
train_generator = datagen.flow_from_directory(
    data_dir,
    target_size=(224, 224),
    batch_size=16,             # 少量資料建議使用小 batch size，訓練較穩定
    class_mode='categorical',
    subset='training'
)

# 讀取驗證資料 (20%)
validation_generator = datagen.flow_from_directory(
    data_dir,
    target_size=(224, 224),
    batch_size=16,
    class_mode='categorical',
    subset='validation'
)

print(f"🎉 成功讀取圖片！風格標籤對應順序為：{train_generator.class_indices}")

# =====================================================================
# 步驟 3: 打造你的 CNN 模型 (使用轉移學習 MobileNetV2)
# =====================================================================
print("🤖 正在載入 Google 預訓練模型 MobileNetV2...")
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False  # 凍結基礎模型，只訓練我們新加的風格層

# 疊加自訂分類層
model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),                  # 提高 Dropout 比例到 0.5，防止死記硬背
    layers.Dense(3, activation='softmax') # 輸出 3 個風格的機率
])

# 編譯模型
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# =====================================================================
# 步驟 4: 開始訓練 AI 模型
# =====================================================================
print("🚀 AI 開始學習你的動漫風格... 這可能需要幾分鐘，請稍候...")
history = model.fit(
    train_generator,
    epochs=20,                 # 圖片少，跑 20 輪就足夠了
    validation_data=validation_generator
)

# =====================================================================
# 步驟 5: 儲存模型大腦與繪製圖表
# =====================================================================
# 儲存路徑為你雲端硬碟的 anime_style_project 資料夾內
save_path = '/content/drive/MyDrive/anime_style_project/style_model.h5'
model.save(save_path)
print(f"💾 🎉 模型已成功儲存至你的雲端硬碟！檔案名稱為：{save_path}")

# 自動幫你畫出準確率圖表
print("📈 正在生成訓練準確率圖表...")
plt.figure(figsize=(8, 5))
plt.plot(history.history['accuracy'], label='Train Accuracy (訓練準確率)')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy (驗證準確率)')
plt.legend()
plt.title('AI Model Learning Progress (模型學習進度)')
plt.xlabel('Epochs (輪次)')
plt.ylabel('Accuracy (準確率)')
plt.grid(True)
plt.show()